--Câu 1--
CREATE DATABASE QL_GIACONG
GO

USE QL_GIACONG;
CREATE TABLE MUCGIACONG (
  MAMUCGIACONG VARCHAR(50) NOT NULL PRIMARY KEY,
  TENMUCGIACONG NVARCHAR(50) NOT NULL,
  DVT NVARCHAR(20) NOT NULL,
  DONGIA DECIMAL(18, 0) NOT NULL
);
GO

CREATE TABLE NHATKYGC (
  MANKGC VARCHAR(50) PRIMARY KEY NOT NULL,
  TENKHACHHANG NVARCHAR(50) NOT NULL,
  NGAYNHANHANG DATE NOT NULL,
  NGAYGIAOHANG DATE NOT NULL,
  PTGIAOHANG NVARCHAR(20)NOT NULL,
  DIACHI NVARCHAR(100)NULL,
  DATHANHTOAN BIT NOT NULL,
  CONSTRAINT CHEKC_NGAY_GIAO_NHAN CHECK (NGAYGIAOHANG >= NGAYNHANHANG)
);
GO

CREATE TABLE CHITIET (
  MANKGC VARCHAR(50) NOT NULL,
  MAMUCGIACONG VARCHAR(50) NOT NULL,
  SOLUONG INT NOT NULL,
  PRIMARY KEY (MANKGC, MAMUCGIACONG),
  FOREIGN KEY (MANKGC) REFERENCES NHATKYGC(MANKGC),
  FOREIGN KEY (MAMUCGIACONG) REFERENCES MUCGIACONG(MAMUCGIACONG)
);
GO

INSERT INTO MUCGIACONG (MAMUCGIACONG, TENMUCGIACONG, DVT, DONGIA)
VALUES ('GC1', N'Viền Mái', 'met', 120000),
       ('GC2', N'Tiện Trục Máy Cán', 'cái', 200000),
       ('GC3', N'Máng Xối Biên', 'met', 210000),
	   ('GC4', N'Ép Nhựa', N'met khối', 130000);
GO

INSERT INTO NHATKYGC (MANKGC, TENKHACHHANG, NGAYNHANHANG, NGAYGIAOHANG, PTGIAOHANG, DIACHI, DATHANHTOAN)
VALUES ('NK1', N'Nguyễn Văn An', '2017-03-02', '2017-04-03', N'Tại Xưởng', NULL, 1),
       ('NK2', N'Trần Thanh Tuấn', '2017-03-02', '2017-03-04', N'Tại nhà khách hàng', N'15 Lê lợi', 1),
       ('NK3', N'Lê Thị Thu', '2017-04-15', '2017-04-19', N'tại Xưởng', NULL, 0);
GO

INSERT INTO CHITIET (MANKGC, MAMUCGIACONG, SOLUONG)
VALUES ('NK1', 'GC1', 4),
       ('NK1', 'GC2', 5),
       ('NK2', 'GC1', 6),
       ('NK2', 'GC3', 4),
	   ('NK2', 'GC4', 50);
GO
--Câu 2--
--a)--

UPDATE NHATKYGC
SET DATHANHTOAN = 1
WHERE TENKHACHHANG = N'Lê Thị Thu';
GO
--b)--

SELECT N.TENKHACHHANG,N.NGAYGIAOHANG,M.MAMUCGIACONG,M.TENMUCGIACONG,C.SOLUONG,M.DONGIA, (C.SOLUONG*M.DONGIA) AS THANHTIEN
FROM CHITIET C
INNER JOIN MUCGIACONG M ON M.MAMUCGIACONG= C.MAMUCGIACONG
INNER JOIN NHATKYGC N ON N.MANKGC = C.MANKGC
GO
--c)--
SELECT TOP 1 WITH TIES A.MAMUCGIACONG,TENMUCGIACONG,SUM(SOLUONG*DONGIA) AS 'DOANH THU'
FROM DBO.MUCGIACONG A INNER JOIN DBO.CHITIET B ON A.MAMUCGIACONG = B.MAMUCGIACONG
GROUP BY A.MAMUCGIACONG,TENMUCGIACONG
ORDER BY 'DOANH THU' DESC
--d)--
SELECT  TOP 1 WITH TIES A.MANKGC,TENKHACHHANG,SUM (SOLUONG) AS 'SO LAN GIA CONG'
FROM (DBO.NHATKYGC A INNER JOIN DBO.CHITIET B ON A.MANKGC = B.MANKGC) INNER JOIN DBO.MUCGIACONG C ON B.MAMUCGIACONG = C.MAMUCGIACONG
GROUP BY A.MANKGC,TENKHACHHANG
ORDER BY 'SO LAN GIA CONG' DESC
--Câu 6--
BACKUP DATABASE QL_GIACONG
TO DISK = 'D:\DE170592_NguyenVanHon\QL_GIACONG_Backup.bak';
