USE DE170592_NguyenVanHon;
CREATE TABLE MUCGIACONG (
  MAMUCGIACONG NVARCHAR NOT NULL PRIMARY KEY,
  TENMUCGIACONG NVARCHAR(50) NOT NULL,
  DVT NVARCHAR(20) NOT NULL,
  DONGIA DECIMAL(18, 0) NOT NULL
);

CREATE TABLE NHATKYGC (
  MANKGC NVARCHAR PRIMARY KEY NOT NULL,
  TENKHACHHANG NVARCHAR(50) NOT NULL,
  NGAYNHANHANG DATE NOT NULL,
  NGAYGIAOHANG DATE NOT NULL,
  PTGIAOHANG NVARCHAR(20)NOT NULL,
  DIACHI NVARCHAR(100)NULL,
  DATHANHTOAN BIT NOT NULL,
  CONSTRAINT chk_ngaygiaohang CHECK (NGAYGIAOHANG >= NGAYNHANHANG)
);

CREATE TABLE CHITIET (
  MANKGC NVARCHAR NOT NULL,
  MAMUCGIACONG NVARCHAR NOT NULL,
  SOLUONG INT NOT NULL,
  PRIMARY KEY (MANKGC, MAMUCGIACONG),
  FOREIGN KEY (MANKGC) REFERENCES NHATKYGC(MANKGC),
  FOREIGN KEY (MAMUCGIACONG) REFERENCES MUCGIACONG(MAMUCGIACONG)
);

INSERT INTO MUCGIACONG (MAMUCGIACONG, TENMUCGIACONG, DVT, DONGIA)
VALUES ('GC1', 'Viền Mái', 'met', 120000),
       ('GC2', 'Tiện Trục Máy Cán', 'cái', 200000),
       ('GC3', 'Máng Xối Biên', 'met', 210000),
	   ('GC4', 'Ép Nhựa', 'met khối', 130000);

INSERT INTO NHATKYGC (MANKGC, TENKHACHHANG, NGAYNHANHANG, NGAYGIAOHANG, PTGIAOHANG, DIACHI, DATHANHTOAN)
VALUES ('NK1', 'Nguyễn Văn An', '2017-03-02', '2017-04-03', 'Tại Xưởng', NULL, 1),
       ('NK2', 'Trần Thanh Tuấn', '2017-03-02', '2017-03-04', 'Tại nhà khách hàng', '15 Lê lợi', 1),
       ('NK3', 'Lê Thị Thu', '2017-04-15', '2017-04-09', 'tại Xưởng', NULL, 0);

INSERT INTO CHITIET (MANKGC, MAMUCGIACONG, SOLUONG)
VALUES ('NK1', 'GC1', 4),
       ('NK1', 'GC2', 5),
       ('NK2', 'GC1', 6),
       ('NK2', 'GC3', 4),
	   ('NK2', 'GC4', 50);
--2--
--a)
UPDATE NHATKYGC
SET DATHANHTOAN = 1
WHERE TENKHACHHANG = 'Lê Thị Thu';
--b)
SELECT NHATKYGC.TENKHACHHANG, NHATKYGC.NGAYGIAOHANG, CHITIET.MAMUCGIACONG, MUCGIACONG.TENMUCGIACONG, CHITIET.SOLUONG, MUCGIACONG.DONGIA, (CHITIET.SOLUONG * MUCGIACONG.DONGIA) AS THANHTIEN
FROM NHATKYGC
INNER JOIN CHITIET ON NHATKYGC.MANKGC = CHITIET.MANKGC
INNER JOIN MUCGIACONG ON CHITIET.MAMUCGIACONG = MUCGIACONG.MAMUCGIACONG;
--c)
SELECT MAMUCGIACONG, TENMUCGIACONG, (SOLUONG * DONGIA) AS DOANHTHU
FROM MUCGIACONG
ORDER BY DOANHTHU DESC
LIMIT 1;
--d)
SELECT TENKHACHHANG, COUNT(*) AS SOLUONG_GIACONG
FROM NHATKYGC
GROUP BY TENKHACHHANG
ORDER BY SOLUONG_GIACONG DESC
LIMIT 1;
